defaults: &defaults
  facebook_app_id: "412125618923008"
  facebook_secret: "59647e1587b2f2712af2abc5bdfd276c"

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults